//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIAPP.DataService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RIAPP.DataService.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association has empty name.
        /// </summary>
        internal static string ERR_ASSOC_EMPTY_NAME {
            get {
                return ResourceManager.GetString("ERR_ASSOC_EMPTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association: {0} contains invalid childDbSetName: {1}.
        /// </summary>
        internal static string ERR_ASSOC_INVALID_CHILD {
            get {
                return ResourceManager.GetString("ERR_ASSOC_INVALID_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association: {0} contains invalid child field name: {1}.
        /// </summary>
        internal static string ERR_ASSOC_INVALID_CHILD_FIELD {
            get {
                return ResourceManager.GetString("ERR_ASSOC_INVALID_CHILD_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association: {0} has childToParentName: {1} which already exists in child DbSet&apos;s fields.
        /// </summary>
        internal static string ERR_ASSOC_INVALID_NAV_FIELD {
            get {
                return ResourceManager.GetString("ERR_ASSOC_INVALID_NAV_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association: {0} contains invalid parentDbSetName: {1}.
        /// </summary>
        internal static string ERR_ASSOC_INVALID_PARENT {
            get {
                return ResourceManager.GetString("ERR_ASSOC_INVALID_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association: {0} contains invalid parent field name: {1}.
        /// </summary>
        internal static string ERR_ASSOC_INVALID_PARENT_FIELD {
            get {
                return ResourceManager.GetString("ERR_ASSOC_INVALID_PARENT_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} does not exist on entity type {1}.
        /// </summary>
        internal static string ERR_CAN_NOT_SET_PARENT_FIELD {
            get {
                return ResourceManager.GetString("ERR_CAN_NOT_SET_PARENT_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query result&apos;s chunk is not found in cache.
        /// </summary>
        internal static string ERR_CHUNK_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_CHUNK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} is disabled on the {1}.
        /// </summary>
        internal static string ERR_CODEGEN_DISABLED {
            get {
                return ResourceManager.GetString("ERR_CODEGEN_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity: {0} delete data method is not implemented by {1}.
        /// </summary>
        internal static string ERR_DB_DELETE_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("ERR_DB_DELETE_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbSetInfo {0} has empty EntityType property.
        /// </summary>
        internal static string ERR_DB_ENTITYTYPE_INVALID {
            get {
                return ResourceManager.GetString("ERR_DB_ENTITYTYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity: {0} insert data method is not implemented by {1}.
        /// </summary>
        internal static string ERR_DB_INSERT_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("ERR_DB_INSERT_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity: {0} update data method is not implemented by {2}.
        /// </summary>
        internal static string ERR_DB_UPDATE_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("ERR_DB_UPDATE_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is autogenerated, and does not allow editing.
        /// </summary>
        internal static string ERR_FIELD_IS_AUTO_GENERATED {
            get {
                return ResourceManager.GetString("ERR_FIELD_IS_AUTO_GENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field  &apos;{0}&apos;  is not nullable.
        /// </summary>
        internal static string ERR_FIELD_IS_NOT_NULLABLE {
            get {
                return ResourceManager.GetString("ERR_FIELD_IS_NOT_NULLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation path {0} for included result is invalid.
        /// </summary>
        internal static string ERR_INCL_NAVIG_INVALID {
            get {
                return ResourceManager.GetString("ERR_INCL_NAVIG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Method  was invoked outside the scope of it&apos;s application.
        /// </summary>
        internal static string ERR_METH_APPLY_INVALID {
            get {
                return ResourceManager.GetString("ERR_METH_APPLY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with name {0} is not found among service methods.
        /// </summary>
        internal static string ERR_METH_NAME_INVALID {
            get {
                return ResourceManager.GetString("ERR_METH_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not return included child entities for multypage requests.
        /// </summary>
        internal static string ERR_MULTYPAGE_REQUEST {
            get {
                return ResourceManager.GetString("ERR_MULTYPAGE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} does not contain property {1}.
        /// </summary>
        internal static string ERR_PROPERTY_IS_MISSING {
            get {
                return ResourceManager.GetString("ERR_PROPERTY_IS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is readonly.
        /// </summary>
        internal static string ERR_PROPERTY_IS_READONLY {
            get {
                return ResourceManager.GetString("ERR_PROPERTY_IS_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query with name {0} is not found among service query methods.
        /// </summary>
        internal static string ERR_QUERY_NAME_INVALID {
            get {
                return ResourceManager.GetString("ERR_QUERY_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity: {0} does not support changeType: {1}.
        /// </summary>
        internal static string ERR_REC_CHANGETYPE_INVALID {
            get {
                return ResourceManager.GetString("ERR_REC_CHANGETYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity: {0} has no  field with the name: {1} .
        /// </summary>
        internal static string ERR_REC_FIELDNAME_INVALID {
            get {
                return ResourceManager.GetString("ERR_REC_FIELDNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been changed by another user..
        /// </summary>
        internal static string ERR_REC_HAS_BEEN_CHANGED {
            get {
                return ResourceManager.GetString("ERR_REC_HAS_BEEN_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh method for {0} is not implemented by service {1}.
        /// </summary>
        internal static string ERR_REC_REFRESH_INVALID {
            get {
                return ResourceManager.GetString("ERR_REC_REFRESH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowInfo for the entity: {0} has invalid primary key: {1} value.
        /// </summary>
        internal static string ERR_ROWINFO_PKVAL_INVALID {
            get {
                return ResourceManager.GetString("ERR_ROWINFO_PKVAL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted items has validation errors.
        /// </summary>
        internal static string ERR_SVC_CHANGES_ARENOT_VALID {
            get {
                return ResourceManager.GetString("ERR_SVC_CHANGES_ARENOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access is denied. Please, ask administrator to assign user rights to your account: &quot;{0}&quot;..
        /// </summary>
        internal static string ERR_USER_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ERR_USER_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid datatype value {0}.
        /// </summary>
        internal static string ERR_VAL_DATATYPE_INVALID {
            get {
                return ResourceManager.GetString("ERR_VAL_DATATYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value has invalid datetime value format {0}.
        /// </summary>
        internal static string ERR_VAL_DATEFORMAT_INVALID {
            get {
                return ResourceManager.GetString("ERR_VAL_DATEFORMAT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} value exceeds maximum length: {1}.
        /// </summary>
        internal static string ERR_VAL_EXCEEDS_MAXLENGTH {
            get {
                return ResourceManager.GetString("ERR_VAL_EXCEEDS_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} value does not match rules for the value format.
        /// </summary>
        internal static string ERR_VAL_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("ERR_VAL_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} value has invalid original value.
        /// </summary>
        internal static string ERR_VAL_ORIGINAL_INVALID {
            get {
                return ResourceManager.GetString("ERR_VAL_ORIGINAL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} value does not falls inside the allowed range of values {1}.
        /// </summary>
        internal static string ERR_VAL_RANGE_NOT_VALID {
            get {
                return ResourceManager.GetString("ERR_VAL_RANGE_NOT_VALID", resourceCulture);
            }
        }
    }
}
