using System;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Web.Script.Serialization;
using System.Collections.Generic;

namespace RIAPP.DataService
{
    /// <summary>
    /// Stores field description (it's attributes)
    /// </summary>
    [DataContract]
    public class FieldInfo
    {
        private FieldInfoList _nested;

        public FieldInfo()
        {
            this.isPrimaryKey = 0;
            this.dataType = DataType.None;
            this.isNullable = true;
            this.maxLength = -1;
            this.isReadOnly = false;
            this.isAutoGenerated = false;
            this.allowClientDefault = false;
            this.dateConversion = DateConversion.None;
            this.fieldType = FieldType.None;
            this.isNeedOriginal = true;
          
            this.range = "";
            this.regex = "";
            this.dependentOn = "";
            this._ordinal = -1;
        }

        [DataMember]
        public string fieldName
        {
            get;
            set;
        }
        
        [DefaultValue((short)0)]
        [DataMember]
        [Description("If this field is a primary key then it must be greater then 0")]
        public short isPrimaryKey
        {
            get;
            set;
        }

        [DataMember]
        [Description("Sets value type, for example - Float, String")]
        public DataType dataType
        {
            get;
            set;
        }

        [DefaultValue(true)]
        [DataMember]
        public bool isNullable
        {
            get;
            set;
        }

        [DefaultValue(false)]
        [DataMember]
        public bool isReadOnly
        {
            get;
            set;
        }

        [DefaultValue(false)]
        [DataMember]
        [Description("On insert the value is automatically generated on the server")]
        public bool isAutoGenerated
        {
            get;
            set;
        }

        [DefaultValue(true)]
        [DataMember]
        public bool isNeedOriginal
        {
            get;
            set;
        }

        [DefaultValue((short)-1)]
        [DataMember]
        [Description("Sets the limit on text size, on value editing")]
        public short maxLength
        {
            get;
            set;
        }

        [DefaultValue(DateConversion.None)]
        [DataMember]
        [Description("Determines how to convert dates between server and client")]
        public DateConversion dateConversion
        {
            get;
            set;
        }

        [DefaultValue(false)]
        [DataMember]
        [Description("Applies when value is set readonly, and means that on insert it's value can be assigned on the client")]
        public bool allowClientDefault
        {
            get;
            set;
        }

        /// <summary>
        /// to check values for being inside the allowed range
        /// set range as minBound,maxBound to check for lower and upper bounds
        /// set range as minBound, to check for only lower bound or
        /// set range as ,naxBound to check for only upper bound
        /// as for a example 0,100 or 0, or ,100
        /// for dates format must be yyyy-MM-dd
        /// </summary>
        [DefaultValue("")]
        [DataMember]
        public string range
        {
            get;
            set;
        }

        /// <summary>
        /// to check values with regex expression
        /// set regex that value must match
        /// </summary>
        [DefaultValue("")]
        [DataMember]
        public string regex
        {
            get;
            set;
        }

        [DefaultValue(FieldType.None)]
        [DataMember]
        public FieldType fieldType
        {
            get;
            set;
        }

        /// <summary>
        /// if this field is a calculated field
        /// this property can return a string of fields on which this calculated field is dependent
        /// each field is separated by comma
        /// </summary>
        [DefaultValue("")]
        [DataMember]
        public string dependentOn
        {
            get;
            set;
        }

        /// <summary>
        /// If the field is a complex type field
        /// it returns a list of its properties
        /// and each child property can be also a complex type property 
        /// </summary>
        [DataMember]
        public FieldInfoList nested
        {
            get {
                if (this.fieldType == FieldType.Object && this._nested == null)
                {
                    this._nested = new FieldInfoList();
                }
                return this._nested; 
            }
            set { _nested = value; }
        }

        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [IgnoreDataMember]
        [ScriptIgnore]
        public int _ordinal
        {
            get;
            set;
        }

        //It is used only for Navigation and ComplexType fields
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [IgnoreDataMember]
        [ScriptIgnore]
        public string _TypeScriptDataType
        {
            get;
            set;
        }

        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [IgnoreDataMember]
        [ScriptIgnore]
        public string _FullName
        {
            get;
            set;
        }
    }

}
